/*
 * This file is generated by jOOQ.
 */
package com.scenepin.infra.jooq.keys


import com.scenepin.infra.jooq.tables.Bookmarks
import com.scenepin.infra.jooq.tables.Tags
import com.scenepin.infra.jooq.tables.VideoTags
import com.scenepin.infra.jooq.tables.Videos
import com.scenepin.infra.jooq.tables.records.BookmarksRecord
import com.scenepin.infra.jooq.tables.records.TagsRecord
import com.scenepin.infra.jooq.tables.records.VideoTagsRecord
import com.scenepin.infra.jooq.tables.records.VideosRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val BOOKMARKS_PKEY: UniqueKey<BookmarksRecord> = Internal.createUniqueKey(Bookmarks.BOOKMARKS, DSL.name("bookmarks_pkey"), arrayOf(Bookmarks.BOOKMARKS.ID), true)
val TAGS_NAME_KEY: UniqueKey<TagsRecord> = Internal.createUniqueKey(Tags.TAGS, DSL.name("tags_name_key"), arrayOf(Tags.TAGS.NAME), true)
val TAGS_PKEY: UniqueKey<TagsRecord> = Internal.createUniqueKey(Tags.TAGS, DSL.name("tags_pkey"), arrayOf(Tags.TAGS.ID), true)
val VIDEO_TAGS_PKEY: UniqueKey<VideoTagsRecord> = Internal.createUniqueKey(VideoTags.VIDEO_TAGS, DSL.name("video_tags_pkey"), arrayOf(VideoTags.VIDEO_TAGS.VIDEO_ID, VideoTags.VIDEO_TAGS.TAG_ID), true)
val VIDEOS_PKEY: UniqueKey<VideosRecord> = Internal.createUniqueKey(Videos.VIDEOS, DSL.name("videos_pkey"), arrayOf(Videos.VIDEOS.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val BOOKMARKS__BOOKMARKS_VIDEO_ID_FKEY: ForeignKey<BookmarksRecord, VideosRecord> = Internal.createForeignKey(Bookmarks.BOOKMARKS, DSL.name("bookmarks_video_id_fkey"), arrayOf(Bookmarks.BOOKMARKS.VIDEO_ID), com.scenepin.infra.jooq.keys.VIDEOS_PKEY, arrayOf(Videos.VIDEOS.ID), true)
val VIDEO_TAGS__VIDEO_TAGS_TAG_ID_FKEY: ForeignKey<VideoTagsRecord, TagsRecord> = Internal.createForeignKey(VideoTags.VIDEO_TAGS, DSL.name("video_tags_tag_id_fkey"), arrayOf(VideoTags.VIDEO_TAGS.TAG_ID), com.scenepin.infra.jooq.keys.TAGS_PKEY, arrayOf(Tags.TAGS.ID), true)
val VIDEO_TAGS__VIDEO_TAGS_VIDEO_ID_FKEY: ForeignKey<VideoTagsRecord, VideosRecord> = Internal.createForeignKey(VideoTags.VIDEO_TAGS, DSL.name("video_tags_video_id_fkey"), arrayOf(VideoTags.VIDEO_TAGS.VIDEO_ID), com.scenepin.infra.jooq.keys.VIDEOS_PKEY, arrayOf(Videos.VIDEOS.ID), true)
