/*
 * This file is generated by jOOQ.
 */
package com.scenepin.infra.jooq.tables


import com.scenepin.infra.jooq.Public
import com.scenepin.infra.jooq.indexes.IDX_BOOKMARKS_TIMESTAMP
import com.scenepin.infra.jooq.indexes.IDX_BOOKMARKS_VIDEO_ID
import com.scenepin.infra.jooq.keys.BOOKMARKS_PKEY
import com.scenepin.infra.jooq.keys.BOOKMARKS__BOOKMARKS_VIDEO_ID_FKEY
import com.scenepin.infra.jooq.tables.Videos.VideosPath
import com.scenepin.infra.jooq.tables.records.BookmarksRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Bookmarks(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BookmarksRecord>?,
    parentPath: InverseForeignKey<out Record, BookmarksRecord>?,
    aliased: Table<BookmarksRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BookmarksRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.bookmarks</code>
         */
        val BOOKMARKS: Bookmarks = Bookmarks()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BookmarksRecord> = BookmarksRecord::class.java

    /**
     * The column <code>public.bookmarks.id</code>.
     */
    val ID: TableField<BookmarksRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.bookmarks.video_id</code>.
     */
    val VIDEO_ID: TableField<BookmarksRecord, Long?> = createField(DSL.name("video_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.bookmarks.timestamp</code>.
     */
    val TIMESTAMP: TableField<BookmarksRecord, Long?> = createField(DSL.name("timestamp"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.bookmarks.memo</code>.
     */
    val MEMO: TableField<BookmarksRecord, String?> = createField(DSL.name("memo"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.bookmarks.created_at</code>.
     */
    val CREATED_AT: TableField<BookmarksRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<BookmarksRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BookmarksRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<BookmarksRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.bookmarks</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.bookmarks</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.bookmarks</code> table reference
     */
    constructor(): this(DSL.name("bookmarks"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BookmarksRecord>?, parentPath: InverseForeignKey<out Record, BookmarksRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, BOOKMARKS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class BookmarksPath : Bookmarks, Path<BookmarksRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BookmarksRecord>?, parentPath: InverseForeignKey<out Record, BookmarksRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<BookmarksRecord>): super(alias, aliased)
        override fun `as`(alias: String): BookmarksPath = BookmarksPath(DSL.name(alias), this)
        override fun `as`(alias: Name): BookmarksPath = BookmarksPath(alias, this)
        override fun `as`(alias: Table<*>): BookmarksPath = BookmarksPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_BOOKMARKS_TIMESTAMP, IDX_BOOKMARKS_VIDEO_ID)
    override fun getIdentity(): Identity<BookmarksRecord, Long?> = super.getIdentity() as Identity<BookmarksRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<BookmarksRecord> = BOOKMARKS_PKEY
    override fun getReferences(): List<ForeignKey<BookmarksRecord, *>> = listOf(BOOKMARKS__BOOKMARKS_VIDEO_ID_FKEY)

    private lateinit var _videos: VideosPath

    /**
     * Get the implicit join path to the <code>public.videos</code> table.
     */
    fun videos(): VideosPath {
        if (!this::_videos.isInitialized)
            _videos = VideosPath(this, BOOKMARKS__BOOKMARKS_VIDEO_ID_FKEY, null)

        return _videos;
    }

    val videos: VideosPath
        get(): VideosPath = videos()
    override fun `as`(alias: String): Bookmarks = Bookmarks(DSL.name(alias), this)
    override fun `as`(alias: Name): Bookmarks = Bookmarks(alias, this)
    override fun `as`(alias: Table<*>): Bookmarks = Bookmarks(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Bookmarks = Bookmarks(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Bookmarks = Bookmarks(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Bookmarks = Bookmarks(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Bookmarks = Bookmarks(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Bookmarks = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Bookmarks = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Bookmarks = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Bookmarks = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Bookmarks = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Bookmarks = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Bookmarks = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Bookmarks = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Bookmarks = where(DSL.notExists(select))
}
