/*
 * This file is generated by jOOQ.
 */
package com.scenepin.infra.jooq.tables


import com.scenepin.infra.jooq.Public
import com.scenepin.infra.jooq.keys.TAGS_NAME_KEY
import com.scenepin.infra.jooq.keys.TAGS_PKEY
import com.scenepin.infra.jooq.keys.VIDEO_TAGS__VIDEO_TAGS_TAG_ID_FKEY
import com.scenepin.infra.jooq.tables.VideoTags.VideoTagsPath
import com.scenepin.infra.jooq.tables.Videos.VideosPath
import com.scenepin.infra.jooq.tables.records.TagsRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Tags(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TagsRecord>?,
    parentPath: InverseForeignKey<out Record, TagsRecord>?,
    aliased: Table<TagsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TagsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.tags</code>
         */
        val TAGS: Tags = Tags()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TagsRecord> = TagsRecord::class.java

    /**
     * The column <code>public.tags.id</code>.
     */
    val ID: TableField<TagsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.tags.name</code>.
     */
    val NAME: TableField<TagsRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>public.tags.created_at</code>.
     */
    val CREATED_AT: TableField<TagsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<TagsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TagsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TagsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.tags</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.tags</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.tags</code> table reference
     */
    constructor(): this(DSL.name("tags"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TagsRecord>?, parentPath: InverseForeignKey<out Record, TagsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, TAGS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TagsPath : Tags, Path<TagsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TagsRecord>?, parentPath: InverseForeignKey<out Record, TagsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<TagsRecord>): super(alias, aliased)
        override fun `as`(alias: String): TagsPath = TagsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): TagsPath = TagsPath(alias, this)
        override fun `as`(alias: Table<*>): TagsPath = TagsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<TagsRecord, Long?> = super.getIdentity() as Identity<TagsRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<TagsRecord> = TAGS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<TagsRecord>> = listOf(TAGS_NAME_KEY)

    private lateinit var _videoTags: VideoTagsPath

    /**
     * Get the implicit to-many join path to the <code>public.video_tags</code>
     * table
     */
    fun videoTags(): VideoTagsPath {
        if (!this::_videoTags.isInitialized)
            _videoTags = VideoTagsPath(this, null, VIDEO_TAGS__VIDEO_TAGS_TAG_ID_FKEY.inverseKey)

        return _videoTags;
    }

    val videoTags: VideoTagsPath
        get(): VideoTagsPath = videoTags()

    /**
     * Get the implicit many-to-many join path to the <code>public.videos</code>
     * table
     */
    val videos: VideosPath
        get(): VideosPath = videoTags().videos()
    override fun `as`(alias: String): Tags = Tags(DSL.name(alias), this)
    override fun `as`(alias: Name): Tags = Tags(alias, this)
    override fun `as`(alias: Table<*>): Tags = Tags(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Tags = Tags(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Tags = Tags(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Tags = Tags(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Tags = Tags(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Tags = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Tags = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Tags = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Tags = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Tags = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Tags = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Tags = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Tags = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Tags = where(DSL.notExists(select))
}
