/*
 * This file is generated by jOOQ.
 */
package com.scenepin.infra.jooq.tables


import com.scenepin.infra.jooq.Public
import com.scenepin.infra.jooq.indexes.IDX_VIDEOS_UPDATED_AT
import com.scenepin.infra.jooq.keys.BOOKMARKS__BOOKMARKS_VIDEO_ID_FKEY
import com.scenepin.infra.jooq.keys.VIDEOS_PKEY
import com.scenepin.infra.jooq.keys.VIDEO_TAGS__VIDEO_TAGS_VIDEO_ID_FKEY
import com.scenepin.infra.jooq.tables.Bookmarks.BookmarksPath
import com.scenepin.infra.jooq.tables.Tags.TagsPath
import com.scenepin.infra.jooq.tables.VideoTags.VideoTagsPath
import com.scenepin.infra.jooq.tables.records.VideosRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Videos(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, VideosRecord>?,
    parentPath: InverseForeignKey<out Record, VideosRecord>?,
    aliased: Table<VideosRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<VideosRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.videos</code>
         */
        val VIDEOS: Videos = Videos()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<VideosRecord> = VideosRecord::class.java

    /**
     * The column <code>public.videos.id</code>.
     */
    val ID: TableField<VideosRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.videos.name</code>.
     */
    val NAME: TableField<VideosRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.videos.file_path</code>.
     */
    val FILE_PATH: TableField<VideosRecord, String?> = createField(DSL.name("file_path"), SQLDataType.VARCHAR(1024).nullable(false), this, "")

    /**
     * The column <code>public.videos.thumbnail_path</code>.
     */
    val THUMBNAIL_PATH: TableField<VideosRecord, String?> = createField(DSL.name("thumbnail_path"), SQLDataType.VARCHAR(1024).nullable(false), this, "")

    /**
     * The column <code>public.videos.duration</code>.
     */
    val DURATION: TableField<VideosRecord, Long?> = createField(DSL.name("duration"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.videos.file_size</code>.
     */
    val FILE_SIZE: TableField<VideosRecord, Long?> = createField(DSL.name("file_size"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.videos.created_at</code>.
     */
    val CREATED_AT: TableField<VideosRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.videos.updated_at</code>.
     */
    val UPDATED_AT: TableField<VideosRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<VideosRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<VideosRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<VideosRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.videos</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.videos</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.videos</code> table reference
     */
    constructor(): this(DSL.name("videos"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VideosRecord>?, parentPath: InverseForeignKey<out Record, VideosRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, VIDEOS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class VideosPath : Videos, Path<VideosRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VideosRecord>?, parentPath: InverseForeignKey<out Record, VideosRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<VideosRecord>): super(alias, aliased)
        override fun `as`(alias: String): VideosPath = VideosPath(DSL.name(alias), this)
        override fun `as`(alias: Name): VideosPath = VideosPath(alias, this)
        override fun `as`(alias: Table<*>): VideosPath = VideosPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_VIDEOS_UPDATED_AT)
    override fun getIdentity(): Identity<VideosRecord, Long?> = super.getIdentity() as Identity<VideosRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<VideosRecord> = VIDEOS_PKEY

    private lateinit var _bookmarks: BookmarksPath

    /**
     * Get the implicit to-many join path to the <code>public.bookmarks</code>
     * table
     */
    fun bookmarks(): BookmarksPath {
        if (!this::_bookmarks.isInitialized)
            _bookmarks = BookmarksPath(this, null, BOOKMARKS__BOOKMARKS_VIDEO_ID_FKEY.inverseKey)

        return _bookmarks;
    }

    val bookmarks: BookmarksPath
        get(): BookmarksPath = bookmarks()

    private lateinit var _videoTags: VideoTagsPath

    /**
     * Get the implicit to-many join path to the <code>public.video_tags</code>
     * table
     */
    fun videoTags(): VideoTagsPath {
        if (!this::_videoTags.isInitialized)
            _videoTags = VideoTagsPath(this, null, VIDEO_TAGS__VIDEO_TAGS_VIDEO_ID_FKEY.inverseKey)

        return _videoTags;
    }

    val videoTags: VideoTagsPath
        get(): VideoTagsPath = videoTags()

    /**
     * Get the implicit many-to-many join path to the <code>public.tags</code>
     * table
     */
    val tags: TagsPath
        get(): TagsPath = videoTags().tags()
    override fun `as`(alias: String): Videos = Videos(DSL.name(alias), this)
    override fun `as`(alias: Name): Videos = Videos(alias, this)
    override fun `as`(alias: Table<*>): Videos = Videos(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Videos = Videos(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Videos = Videos(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Videos = Videos(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Videos = Videos(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Videos = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Videos = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Videos = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Videos = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Videos = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Videos = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Videos = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Videos = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Videos = where(DSL.notExists(select))
}
