/*
 * This file is generated by jOOQ.
 */
package com.scenepin.infra.jooq.tables


import com.scenepin.infra.jooq.Public
import com.scenepin.infra.jooq.indexes.IDX_VIDEO_TAGS_TAG_ID
import com.scenepin.infra.jooq.keys.VIDEO_TAGS_PKEY
import com.scenepin.infra.jooq.keys.VIDEO_TAGS__VIDEO_TAGS_TAG_ID_FKEY
import com.scenepin.infra.jooq.keys.VIDEO_TAGS__VIDEO_TAGS_VIDEO_ID_FKEY
import com.scenepin.infra.jooq.tables.Tags.TagsPath
import com.scenepin.infra.jooq.tables.Videos.VideosPath
import com.scenepin.infra.jooq.tables.records.VideoTagsRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class VideoTags(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, VideoTagsRecord>?,
    parentPath: InverseForeignKey<out Record, VideoTagsRecord>?,
    aliased: Table<VideoTagsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<VideoTagsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.video_tags</code>
         */
        val VIDEO_TAGS: VideoTags = VideoTags()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<VideoTagsRecord> = VideoTagsRecord::class.java

    /**
     * The column <code>public.video_tags.video_id</code>.
     */
    val VIDEO_ID: TableField<VideoTagsRecord, Long?> = createField(DSL.name("video_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.video_tags.tag_id</code>.
     */
    val TAG_ID: TableField<VideoTagsRecord, Long?> = createField(DSL.name("tag_id"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<VideoTagsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<VideoTagsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<VideoTagsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.video_tags</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.video_tags</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.video_tags</code> table reference
     */
    constructor(): this(DSL.name("video_tags"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VideoTagsRecord>?, parentPath: InverseForeignKey<out Record, VideoTagsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, VIDEO_TAGS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class VideoTagsPath : VideoTags, Path<VideoTagsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VideoTagsRecord>?, parentPath: InverseForeignKey<out Record, VideoTagsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<VideoTagsRecord>): super(alias, aliased)
        override fun `as`(alias: String): VideoTagsPath = VideoTagsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): VideoTagsPath = VideoTagsPath(alias, this)
        override fun `as`(alias: Table<*>): VideoTagsPath = VideoTagsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_VIDEO_TAGS_TAG_ID)
    override fun getPrimaryKey(): UniqueKey<VideoTagsRecord> = VIDEO_TAGS_PKEY
    override fun getReferences(): List<ForeignKey<VideoTagsRecord, *>> = listOf(VIDEO_TAGS__VIDEO_TAGS_TAG_ID_FKEY, VIDEO_TAGS__VIDEO_TAGS_VIDEO_ID_FKEY)

    private lateinit var _tags: TagsPath

    /**
     * Get the implicit join path to the <code>public.tags</code> table.
     */
    fun tags(): TagsPath {
        if (!this::_tags.isInitialized)
            _tags = TagsPath(this, VIDEO_TAGS__VIDEO_TAGS_TAG_ID_FKEY, null)

        return _tags;
    }

    val tags: TagsPath
        get(): TagsPath = tags()

    private lateinit var _videos: VideosPath

    /**
     * Get the implicit join path to the <code>public.videos</code> table.
     */
    fun videos(): VideosPath {
        if (!this::_videos.isInitialized)
            _videos = VideosPath(this, VIDEO_TAGS__VIDEO_TAGS_VIDEO_ID_FKEY, null)

        return _videos;
    }

    val videos: VideosPath
        get(): VideosPath = videos()
    override fun `as`(alias: String): VideoTags = VideoTags(DSL.name(alias), this)
    override fun `as`(alias: Name): VideoTags = VideoTags(alias, this)
    override fun `as`(alias: Table<*>): VideoTags = VideoTags(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): VideoTags = VideoTags(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): VideoTags = VideoTags(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): VideoTags = VideoTags(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): VideoTags = VideoTags(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): VideoTags = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): VideoTags = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): VideoTags = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): VideoTags = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): VideoTags = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): VideoTags = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): VideoTags = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): VideoTags = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): VideoTags = where(DSL.notExists(select))
}
