/*
 * This file is generated by jOOQ.
 */
package com.scenepin.infra.jooq.tables.references


import com.scenepin.infra.jooq.tables.Bookmarks
import com.scenepin.infra.jooq.tables.Tags
import com.scenepin.infra.jooq.tables.VideoTags
import com.scenepin.infra.jooq.tables.Videos



/**
 * The table <code>public.bookmarks</code>.
 */
val BOOKMARKS: Bookmarks = Bookmarks.BOOKMARKS

/**
 * The table <code>public.tags</code>.
 */
val TAGS: Tags = Tags.TAGS

/**
 * The table <code>public.video_tags</code>.
 */
val VIDEO_TAGS: VideoTags = VideoTags.VIDEO_TAGS

/**
 * The table <code>public.videos</code>.
 */
val VIDEOS: Videos = Videos.VIDEOS
