/*
 * This file is generated by jOOQ.
 */
package com.scenepin.infra.jooq.indexes


import com.scenepin.infra.jooq.tables.Bookmarks
import com.scenepin.infra.jooq.tables.VideoTags
import com.scenepin.infra.jooq.tables.Videos

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_BOOKMARKS_TIMESTAMP: Index = Internal.createIndex(DSL.name("idx_bookmarks_timestamp"), Bookmarks.BOOKMARKS, arrayOf(Bookmarks.BOOKMARKS.VIDEO_ID, Bookmarks.BOOKMARKS.TIMESTAMP), false)
val IDX_BOOKMARKS_VIDEO_ID: Index = Internal.createIndex(DSL.name("idx_bookmarks_video_id"), Bookmarks.BOOKMARKS, arrayOf(Bookmarks.BOOKMARKS.VIDEO_ID), false)
val IDX_VIDEO_TAGS_TAG_ID: Index = Internal.createIndex(DSL.name("idx_video_tags_tag_id"), VideoTags.VIDEO_TAGS, arrayOf(VideoTags.VIDEO_TAGS.TAG_ID), false)
val IDX_VIDEOS_UPDATED_AT: Index = Internal.createIndex(DSL.name("idx_videos_updated_at"), Videos.VIDEOS, arrayOf(Videos.VIDEOS.UPDATED_AT.desc()), false)
