/*
 * This file is generated by jOOQ.
 */
package com.scenepin.infra.jooq.tables.records


import com.scenepin.infra.jooq.tables.Bookmarks

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BookmarksRecord private constructor() : UpdatableRecordImpl<BookmarksRecord>(Bookmarks.BOOKMARKS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var videoId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open var timestamp: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open var memo: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var createdAt: LocalDateTime
        set(value): Unit = set(4, value)
        get(): LocalDateTime = get(4) as LocalDateTime

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised BookmarksRecord
     */
    constructor(id: Long? = null, videoId: Long, timestamp: Long, memo: String, createdAt: LocalDateTime): this() {
        this.id = id
        this.videoId = videoId
        this.timestamp = timestamp
        this.memo = memo
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
