/*
 * This file is generated by jOOQ.
 */
package com.scenepin.infra.jooq.tables.records


import com.scenepin.infra.jooq.tables.VideoTags

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class VideoTagsRecord private constructor() : UpdatableRecordImpl<VideoTagsRecord>(VideoTags.VIDEO_TAGS) {

    open var videoId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open var tagId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, Long?> = super.key() as Record2<Long?, Long?>

    /**
     * Create a detached, initialised VideoTagsRecord
     */
    constructor(videoId: Long, tagId: Long): this() {
        this.videoId = videoId
        this.tagId = tagId
        resetChangedOnNotNull()
    }
}
