/*
 * This file is generated by jOOQ.
 */
package com.scenepin.infra.jooq.tables.records


import com.scenepin.infra.jooq.tables.Videos

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class VideosRecord private constructor() : UpdatableRecordImpl<VideosRecord>(Videos.VIDEOS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var filePath: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var thumbnailPath: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var duration: Long
        set(value): Unit = set(4, value)
        get(): Long = get(4) as Long

    open var fileSize: Long
        set(value): Unit = set(5, value)
        get(): Long = get(5) as Long

    open var createdAt: LocalDateTime
        set(value): Unit = set(6, value)
        get(): LocalDateTime = get(6) as LocalDateTime

    open var updatedAt: LocalDateTime
        set(value): Unit = set(7, value)
        get(): LocalDateTime = get(7) as LocalDateTime

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised VideosRecord
     */
    constructor(id: Long? = null, name: String, filePath: String, thumbnailPath: String, duration: Long, fileSize: Long, createdAt: LocalDateTime, updatedAt: LocalDateTime): this() {
        this.id = id
        this.name = name
        this.filePath = filePath
        this.thumbnailPath = thumbnailPath
        this.duration = duration
        this.fileSize = fileSize
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetChangedOnNotNull()
    }
}
