/*
 * This file is generated by jOOQ.
 */
package com.scenepin.infra.jooq


import com.scenepin.infra.jooq.tables.Bookmarks
import com.scenepin.infra.jooq.tables.Tags
import com.scenepin.infra.jooq.tables.VideoTags
import com.scenepin.infra.jooq.tables.Videos

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.bookmarks</code>.
     */
    val BOOKMARKS: Bookmarks get() = Bookmarks.BOOKMARKS

    /**
     * The table <code>public.tags</code>.
     */
    val TAGS: Tags get() = Tags.TAGS

    /**
     * The table <code>public.video_tags</code>.
     */
    val VIDEO_TAGS: VideoTags get() = VideoTags.VIDEO_TAGS

    /**
     * The table <code>public.videos</code>.
     */
    val VIDEOS: Videos get() = Videos.VIDEOS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Bookmarks.BOOKMARKS,
        Tags.TAGS,
        VideoTags.VIDEO_TAGS,
        Videos.VIDEOS
    )
}
